name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        env:
          REACT_APP_SENTRY_DSN: ${{ vars.REACT_APP_SENTRY_DSN }}
          REACT_APP_RPC_URL_1: ${{ vars.REACT_APP_RPC_URL_1 }}
          REACT_APP_RPC_URL_5: ${{ vars.REACT_APP_RPC_URL_5 }}
          REACT_APP_RPC_URL_59140: ${{ vars.REACT_APP_RPC_URL_59140 }}
        run: |
          yarn
          yarn build

      - name: GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build

      - name: IPFS (Infura)
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}

      - name: IPFS (Pinata)
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}